### ISSUE TITLE
Button Đăng nhập, Đăng ký

### ISSUE THREAD

**Issue by vanvy** [azwebplus/traning-laravel-01#7]
Button có 2 vùng chọn và khi click vào vùng chọn bên ngoài thì không có dialog hiện lên

![image](https://user-images.githubusercontent.com/21197254/41450535-47c86068-701d-11e8-8981-9a300308d2e3.png)

Nếu làm đúng thì sẽ như hình dưới

![image](https://user-images.githubusercontent.com/21197254/41450503-18e703c6-701d-11e8-8065-df79400aaa6d.png)

**Comment by avvotinh** [comment]
Đã xong!
